### ISSUE TITLE
normalization of the language data

### ISSUE THREAD

**Issue by noviluni** [arnavkapoor/number-parser#13]
Some languages have accents, etc. and they are commonly missing, so when trying to do something like this:

```python
>>> parse_number('veintiun', lang='es')
```
it doesn't work, but doing this:

```python
>>> parse_number('veintiún', lang='es')
```

it works. We should normalize the language data to avoid this kind of issue.

**Comment by arnavkapoor** [comment]
Hi thanks for pointing this issue out. I guess the best plan of approach is to normalise strings while creating the language files. Then in the main parser file also we pre-process and normalise the input string. 
https://stackoverflow.com/questions/517923/what-is-the-best-way-to-remove-accents-normalize-in-a-python-unicode-string this seems to be a relevant discussion on the problem. Most of the solutions seem to suggest ```unidecode``` library (GPL license) , however a simpler version of the same library exists [here](https://github.com/kmike/text-unidecode) exists with a less stringent license (artistic license). 
There are other solutions using the default python ```unicodedata``` library  and considering ours is a pretty simple use-case , I will try this out first and in case there are issues we can then go with ```text-unidecode```.

**Comment by noviluni** [comment]
As you, as think is better to avoid using external libraries / dependencies if it's possible. :+1:

**Comment by Gallaecio** [comment]
Just a side note: @arnavkapoor Really good work checking the dependency licenses. I think this is a topic often forgotten (or, in any case, I tend to forget about this) yet really important.

**Comment by arnavkapoor** [comment]
We did end up using the second result from [here](https://stackoverflow.com/questions/517923/what-is-the-best-way-to-remove-accents-normalize-in-a-python-unicode-string) , which doesn't require an external library. 

```
import unicodedata
def strip_accents(s):
   return ''.join(c for c in unicodedata.normalize('NFD', s)
                  if unicodedata.category(c) != 'Mn')
```
It seems to work in most of the case. More details [here](https://github.com/arnavkapoor/number-parser/pull/27#pullrequestreview-453446278) and [here](https://github.com/arnavkapoor/number-parser/pull/27#issuecomment-662984810). Closing this issue for now as #27 adds the normalization.
