### ISSUE TITLE
Updating variable names 

### ISSUE THREAD

**Issue by arnavkapoor** [arnavkapoor/number-parser#20]
The current variables/structure for the data files are as follows :- 
```
info = {
    "UNIT_NUMBERS": { },
    "BASE_NUMBERS": { },
    "MTENS": { },
    "MHUNDREDS": { },
    "MULTIPLIERS": { },
    "VALID_TOKENS": { }
}
```
More information on what each variable stores is [here](https://github.com/arnavkapoor/number-parser/issues/10#issuecomment-650229406). 
However the variable names aren't as descriptive and based on the discussion [here](https://github.com/arnavkapoor/number-parser/pull/19#discussion_r448017612), I plan to change them to the following. 

```
info = {
    "UNIT_NUMBERS": { },
    "DIRECT_NUMBERS": { },
    "TENS": { },
    "HUNDREDS": { },
    "BIG_POWERS_OF_TEN": { },
    "SKIP_TOKENS": [ ]
}
```
The structural change is that skip tokens is no longer a dictionary but directly a list. The rest are variable name changes.
Opinions ?

**Comment by lopuhin** [comment]
New names make a lot more sense, thanks 👍

**Comment by kishan3** [comment]
Looks good to me too ! :+1:

**Comment by noviluni** [comment]
@arnavkapoor

**Comment by noviluni** [comment]
(updated previous comment)
