### ISSUE TITLE
Adding extensive automated tests 

### ISSUE THREAD

**Issue by arnavkapoor** [arnavkapoor/number-parser#26]
I’ve been thinking about how we could extensively test our library against a language to be able to affirm that the library officially supports it.

My first ideas were:
* We should explicitly test all numbers from 0 to 100, as they are really common.
* We should test some different combinations of digits and different lengths of numbers.
* We should test edge cases or special cases for each language.

Doing the first it’s easy, but doing the second is not as easy. We can’t test all numbers, so we need to select a set of different numbers to check. After some time doing different, crazy, things, I got this list:

```
1234
23451
345612
4567123
56781234
678912345
7890123456
89091234567
909812345678
987123456789
98761234567890
876512345678909
7654123456789098
65431234567890987
543212345678909876
4321123456789098765
32101234567890987654
210012345678909876543
1000123456789098765432
1234567890987654321
12345678909876543210
123456789098765432100
1234567890987654321000
```

It’s created by appending the next digit to the end and then moving the first digit to the end (and then doing the same but with the digit before).

It’s not perfect, but I think that it’s diverse enough to be able to say that if the parser works for these cases, it will probably work for the most common existing combinations.

What do you think guys? @arnavkapoor @lopuhin @kishan3

I built [some spiders to scrape different websites](https://github.com/noviluni/get_numbers) to get these numbers in words and added here the datasets: https://github.com/noviluni/numbers-data

Sources:
* https://www.tools4noobs.com/online_tools/number_spell_words/
* https://math.tools/calculator/numbers/words
* https://clevert.com.br/t/en/numbers_to_words/

Unfortunately, they don't support Hindi, but I can search a website supporting Hindi and create a new spider if it's necessary.

If you like this idea, we can use these CSVs directly in the tests (don't worry about this, @arnavkapoor, I could show you how I would do it).

In case you have another idea of input numbers for the tests, I can generate for you a dataset for a lot of locales with the numbers you want.

Let me know what you think or if you have any other idea/approach. :slightly_smiling_face:

_Originally posted by @noviluni in https://github.com/arnavkapoor/number-parser/issues/15#issuecomment-659295377_

**Comment by arnavkapoor** [comment]
Creating a new issue to keep track of the point mentioned by @noviluni to add extensive testing.

**Comment by noviluni** [comment]
Hi @arnavkapoor 
I found that clevert.com.br does support Hindi. I will add the data when having a moment to the repo: https://github.com/noviluni/numbers-data

The only downside is that it has a maximum number supported, so the "permutations" file will be incomplete.

**Comment by noviluni** [comment]
@arnavkapoor 

Data is for hindi is now available:
* [hundreds](https://github.com/noviluni/numbers-data/blob/master/hundreds/hi_hundred_clevert.csv)
* [permutations](https://github.com/noviluni/numbers-data/blob/master/permutations/hi_permutations_clevert.csv)

**Comment by arnavkapoor** [comment]
Thanks a lot @noviluni , I will now add support for hindi too in the latest PR #27. I have also mentioned the planned strategy for adding tests in this PR , please do review whenever possible.

**Comment by arnavkapoor** [comment]
Closing issue as #27 is merged.
